# Generated by Django 4.1.13 on 2024-04-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='records',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_sugar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='body_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(help_text='Height in Inches', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxygen_level',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sleep_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stress_level',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(help_text='Weight in pounds', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
