# Generated by Django 4.1.13 on 2024-04-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_remove_patient_records_patient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
