# Generated by Django 4.1.13 on 2024-04-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
