# Generated by Django 4.1.13 on 2024-04-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
