# Generated by Django 4.1.13 on 2024-04-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
